### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ma3252788** [megvii-research/Iter-E2EDET#10]
Hello, I noticed that in the json file you provided, the format of the picture is png, but as far as I know, the official format is jpg. Have you made any changes?

![](https://ypyssl.machunjie.com/machunjie/20220519185850.png)

**Comment by sorrylag** [comment]
> Hello, I noticed that in the json file you provided, the format of the picture is png, but as far as I know, the official format is jpg. Have you made any changes?
> 
> ![](https://camo.githubusercontent.com/bec3066a48bb108da087b92c7e06538046711c5dbd2026be5589d24d5cc8c5a2/68747470733a2f2f79707973736c2e6d616368756e6a69652e636f6d2f6d616368756e6a69652f32303232303531393138353835302e706e67)

好兄弟 请问你是怎么解决的问题呀 我也遇到了
i meet the same problem, how did u fix that?

**Comment by yexiguafuqihao** [comment]
Just revise the imageDir in the config.py as your own image directory.

**Comment by sorrylag** [comment]
> Just revise the imageDir in the config.py as your own image directory.

Thank you for your reply！I have done that before this problem. But i change images *.jpg to *.png and that works.

**Comment by yexiguafuqihao** [comment]
You can check [this]( https://github.com/megvii-research/Iter-E2EDET/blob/main/detectron2/data/datasets/crowdhuman.py) carefully for the solution.
