### ISSUE TITLE
How to obtain the same accuracy as the paper?

### ISSUE THREAD

**Issue by ma3252788** [megvii-research/Iter-E2EDET#11]
Hello, may I ask why, according to your instructions, when I directly run this command ` python3 train_net.py --num-gpus 1    --config-file configs/50e.6h.500pro.ignore.yaml    --eval-only MODEL.WEIGHTS ../../e2edet_final.pth`, there is only AP value and no MR. in addition, the AP value is also very low, only 82%

Thank you very much for any reply

![image](https://user-images.githubusercontent.com/22229456/169287599-fc6cac01-3f7a-4908-984a-9a7e28d6eb5f.png)

**Comment by yexiguafuqihao** [comment]
emm, please run demo.py in each project for evaluation.

**Comment by ma3252788** [comment]
Thank you for your reply, but it seems that there is no demo.py file in the project

![image](https://user-images.githubusercontent.com/22229456/169495971-f39a96fa-7d81-4c69-be79-8351dbe63984.png)

**Comment by yexiguafuqihao** [comment]
You can download the provided model for fast evaluation, whose performance is reported in our paper. Also, we use Pascal-VOC style evaluation code for $\text{AP}$ and $\text{MR}^{-2}$ evaluation, which is a bit different from that in the COCO.  Sorry, the demo.py is renamed as eval_result.py when we shared the code.

<img width="853" alt="image" src="https://user-images.githubusercontent.com/13798039/169639636-b4686d2c-ae19-4d48-95d1-175e5861f618.png">

**Comment by CarlHuangNuc** [comment]
run  python eval_result.py  ,,  may be some file do not provided...  common code do not publish..

Traceback (most recent call last):
  File "eval_result.py", line 10, in <module>
    from common import *
ModuleNotFoundError: No module named 'common
