### ISSUE TITLE
How to use Cityperson dataset in your project ?

### ISSUE THREAD

**Issue by hbu-cv** [megvii-research/Iter-E2EDET#12]
Thanks for your work ! 
 If I want to use the CityPerson dataset for training and evaluation in your project, do I need to register the dataset with detectron2 ? And how to modify the configuration file?

**Comment by yexiguafuqihao** [comment]
We have registered the CityPerson dataset with detectron2. Please check line #59 in [this](https://github.com/megvii-research/Iter-E2EDET/blob/main/detectron2/data/datasets/builtin.py) for details. Besides, you may need to convert the CityPerson annotation into COCO-style format.
