### ISSUE TITLE
How to get the same accuracy as the paperswithcode website released?

### ISSUE THREAD

**Issue by BubblyYi** [megvii-research/Iter-E2EDET#13]
Hi author! Thanks for your amazing works

I see that you have updated the crowdhuman detection performance on the[ paperswitchcode website](https://paperswithcode.com/sota/object-detection-on-crowdhuman-full-body) to 94.1 AP. Could you please update the configuration file of the current SOTA results?

Waiting for your reply!
James

**Comment by yexiguafuqihao** [comment]
We only replace the backbone of R-50 with Swin-L and keep the other setting identical.  And then the performance that reported in the supplement can be achieved.

**Comment by zyayoung** [comment]
Code and checkpoint for SOTA performance on paperswitchcode.com are released in this [repo](https://github.com/zyayoung/Iter-Deformable-DETR).

**Comment by BubblyYi** [comment]
> Code and checkpoint for SOTA performance on paperswitchcode.com are released in this [repo](https://github.com/zyayoung/Iter-Deformable-DETR).

Thank you! This would be very helpful.
