### ISSUE TITLE
the annotations file have been deleted

### ISSUE THREAD

**Issue by NingYuanLin** [megvii-research/Iter-E2EDET#2]
I want to download annotations from [here](https://drive.google.com/file/d/1590h2fo7NJgLOJQiEPinZPbLMPDS1kw9/view?usp=sharing).
But the file seems to have been deleted.

**Comment by yexiguafuqihao** [comment]
Now you can download the annotations from [here](https://drive.google.com/file/d/11TKQWUNDf63FbjLHU9iEASm2nE7exgF8/view?usp=sharing).

**Comment by NingYuanLin** [comment]
Tranks.谢谢~
