### ISSUE TITLE
Question about test single image

### ISSUE THREAD

**Issue by jwgdmkj** [megvii-research/Iter-E2EDET#24]
Hello.
I am a student who studies Detection.
Which file should I use to put the single image I have in your code and run it?
I'd appreciate it if you could answer.
Thank you.

**Comment by yexiguafuqihao** [comment]
Sorry to tell you there is no script for the single image testing. However, a possible solution is that you need to compile as *.json like val.json with dummy annotations for all the image testing.

**Comment by jwgdmkj** [comment]
OK. Thank you!
