### ISSUE TITLE
question about lable assignment

### ISSUE THREAD

**Issue by bravezzzzzz** [megvii-research/Iter-E2EDET#3]
Hello, author!  Thanks for your work! 
As described in paper that 'A spatial prior is adopted to compute the matching cost C, that is, the center of bounding box _bt_ needs to fall in the corresponding target box.'  I have a few questions.
1. How is the spatial prior adopted to the matching cost C? 
2. When matching cost absorbs the spatial prior, can each GT match a object query? 
3. What will happen to a certain  GT if all the centers of boxes don't fall in it?  
Hoping for your reply!

**Comment by yexiguafuqihao** [comment]
> Hello, author! Thanks for your work! As described in paper that 'A spatial prior is adopted to compute the matching cost C, that is, the center of bounding box _bt_ needs to fall in the corresponding target box.' I have a few questions.
> 
> 1. How is the spatial prior adopted to the matching cost C?
> 2. When matching cost absorbs the spatial prior, can each GT match a object query?
> 3. What will happen to a certain  GT if all the centers of boxes don't fall in it?
>    Hoping for your reply!

a.You can check the code in the line of #239 in https://github.com/megvii-research/Iter-E2EDET/blob/main/projects/crowd-e2e-sparse-rcnn/models/matcher.py for the details. And this can still ensure each GT could be matched with only one query. 

b. The GT will not participate in the procedure of computing the supervised losses.

**Comment by liuyang-ict** [comment]
Hi colleagues, I have a little question about the ablation.
How does performance change when replacing the original assignment with the hierarchical bipartite matching?

**Comment by yexiguafuqihao** [comment]
We tried the one-to-one label assignment from a global perspective. Specifically, we first include both reserved queries and noisy ones to perform Hungarian Matching globally to separate positives and negatives. Those reserved queries do not respond to loss computations. Results show comparable performance.

**Comment by liuyang-ict** [comment]
In my opinion, both global and hierarchical assignments are equivalent. As we all know, Hungarian matching has already considered the class score (corresponding to the class cost in the original source code). Such class cost enables the matcher to identify the reserved and noisy queries.

**Comment by liuyang-ict** [comment]
Maybe hierarchical assignment pays more attention to the class score, while the global assignment is more focused on localization costs (giou&l1) than class ones.

**Comment by yexiguafuqihao** [comment]
We design the hierarchical matcher from the intuition that matched targets should be removed from the ground-truths to ensure the noisy queries properly match with the rest ones.
