### ISSUE TITLE
A question about installing

### ISSUE THREAD

**Issue by tfsxyz** [megvii-research/Iter-E2EDET#7]
I saw your paper on the Internet.Your work in objecting the people especially in crowded scene is really amazing.I want to recurrent your work,so I install by your README.md.But after I runs the step one:Install and build libs.
git clone https://github.com/megvii-model/Iter-E2EDET.git
cd Iter-E2EDET
python3 setup.py build develop
And I also success.But I do not find the config.py,also 50e.6h.500pro.ignore.yaml.
Please what I should do.Thank you.

**Comment by yexiguafuqihao** [comment]
Just run the script below and you can see the target file.
 cd projects/sparse-rcnn-baseline
sh run_train.sh will run the training procedure.
sh run_test.sh will run the testing procedure.
