### ISSUE TITLE
No module named 'config'

### ISSUE THREAD

**Issue by CatchBeliF-TAT** [megvii-research/Iter-E2EDET#8]
Sorry to bother you!
File "/xxx/Iter-E2EDET/detectron2/data/datasets/builtin.py", line 37, in <module>
    from config import config
ModuleNotFoundError: No module named 'config'
I want to know the config is which one.

**Comment by yexiguafuqihao** [comment]
You need to get into projects/sparse-rcnn-baseline then run:
sh run_train.sh for training or sh run_test.sh. Everything will be fine.
